name: spd-ai
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - gymnasium
    - stable-baselines3
    - sb3-contrib
    - torch
    - numpy
    - opencv-python
    - pyzmq
    - pandas
    - matplotlib
    - mss
    - opencv-python-headless
